### ISSUE TITLE
typo "raw_kracken"

### ISSUE THREAD

**Issue by yuvaramsingh94** [MetaSUB-CAMP/camp_short-read-taxonomy#2]
Hi,
 there is a typo in the Snakemake file `raw_kracken`. also, Kraken is not generating any file named `kreport_classes.tsv`. both these issues are leading to empty bracken output.

https://github.com/MetaSUB-CAMP/camp_short-read-taxonomy/blob/0c90e89d3642260b12754e5543db86830f634971/workflow/Snakefile#L167

Thanks
yuvaram

**Comment by lauren-mak** [comment]
Thanks for finding it! This bug will be addressed in the next update (v0.6).
