### ISSUE TITLE
Bracken results not writing in

### ISSUE THREAD

**Issue by qiutip** [MetaSUB-CAMP/camp_short-read-taxonomy#3]
Under the snakefile and rule bracken, one of the shell lines responsible for writing in bracken results is commented out.

<img width="1022" alt="issue_snakefile_bracken" src="https://github.com/MetaSUB-CAMP/camp_short-read-taxonomy/assets/20021567/edf35304-4835-4184-970e-98172d7fc25e">

**Comment by lauren-mak** [comment]
Thanks for finding it! This bug will be addressed in the next update (v0.6).
