### ISSUE TITLE
unable to install bbtools

### ISSUE THREAD

**Issue by lmszydlowski** [MetaSUB-CAMP/camp_short-read-taxonomy#4]
I tried creating conda environment (step 2: configs/conda/short-read-taxonomy.yaml), but it fails due to inability to install bbtools.

I tried to install it manually from its channel (-agbiome) but it doesn't work too.

**Comment by lauren-mak** [comment]
Hi! The bbtools suite needs to be installed directly from SourceForge with the following commands:
```
https://sourceforge.net/projects/bbmap/files/latest/download
tar -xzf download
```
After installation, the location of the executable (called `bbmap/bbmask.sh`) needs to be added to `test_data/parameters.yaml` and `configs/parameters.yaml` under the parameter `bbmask_scr`.
